version: '3.1'

services:
  salaries:
    image: mariadb
    container_name: salaries
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=salaries
    ports:
      - "3306:3306"
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  adminer:
    image: adminer
    ports:
      - "8084:8080"
  companies:
    image: postgres
    container_name: companies
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: companies
    ports:
      - "5433:5432"
  authdb:
    image: postgres
    container_name: authdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5434:5432"
#    volumes:
#      - postgres_data
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - cache:/data
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  rabbit:
    image: rabbitmq:3.7.7-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    labels:
      NAME: rabbitmq
volumes:
  mariadb_data:
    driver: local
  postgres_data:
    driver: local
  cache:
    driver: local

networks:
  monitoring: