server:
  port: 8222
eureka:
  client:
    register-with-eureka: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: companies
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/companies/**
        - id: salaries
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/salary/**
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/tokens/**,/api/v1/users/**,/api/v1/roles/**