eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: salary-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/salaries?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
application:
  config:
    auth-url: http://localhost:8080/api/v1/
  kafka:
    auth-topic: auth-topic